server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: event-service
          uri: http://event-service:8082
          predicates:
            - Path=/events/**
          filters:
            - StripPrefix=1
            - JwtFilter
        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - JwtFilter